stages:
  - test

test:
  stage: test
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  parallel: 5
  script:
    # install dependencies
    - npm ci
    # run Cypress testss
    - DBS_USERNAME="suraj+amazon@evolveasia.co" DBS_PASSWORD="Evolve@123" npm run cy:run_process
  only:
    - automation
  artifacts:
    paths:
      - cypress/screenshots/
      - cypress/videos/
      - cypress/reports/